services:
  app:
    build:
      context: ./
      target: production
      no_cache: true
    environment:
      - hibernate_connection_password=${DB_PASS}
      - hibernate_connection_username=${DB_USERNAME}
      - hibernate_connection_url=jdbc:mysql://dp-db:3306/${DB}?createDatabaseIfNotExist=true
    ports:
      - "8080:8080"
      - "8000:8000"
    depends_on:
      - db
    networks:
      - dp-net
    container_name: dp_app
    restart: on-failure
  
  db:
    image: mysql:latest
    # env_file:
    #   - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
    # volumes:
    #   - mysql_data:/var/lib/mysql
    #   - mysql_config:/etc/mysql/conf.d
    networks:
      - dp-net
    container_name: dp-db

networks:
  dp-net:
    driver: bridge  
volumes:
  mysql_data:
  mysql_config: