services:
  app:
    build:
      context: ./
      target: development
      #no_cache: true
    ports:
      - "8080:8080"
      - "8000:8000"
    depends_on:
      - db
    networks:
      - dp-net
    container_name: dp_app
    restart: on-failure
  
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=MyNewPass
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d
    networks:
      - dp-net
    container_name: dp-db

networks:
  dp-net:
    driver: bridge  
volumes:
  mysql_data:
  mysql_config: